#Simulation parameters
delta_clock: .1 #Simulation time step (ms)
seed: 3141774 #Use 0 for a random seed, Control seed: 3141774
t_steps: 20000
optimizing: 0 #Use 1 when running Bayesian optimization to find parameters
#Test parameters
delay_bt_electrodes: 0         #Define the synaptic delay for the second electrode (ms)
current_stimulus: 7680          #Amount of current stimulus (pA). Typical values: 120, 240, 960, 3840, 7680, 15360 
pulse_duration: 500             #Length of current stimulus (ms)
interval_duration: 2000         #Length of interval between current stimuli (ms)
silence_inhibitory_neurons: 0   #0: Inhibitory neurons connected and firing; 1: Inhibitory neurons disconnected and silenced
noise_removed: 0                #0: Noise added to the network; 1: No noise in the network
#Data analysis parameters
calculate_balance: 0
chop_edges_amount: 0 #5000
convstd_rate: 200
downsampling_convolved: 0
high_pass_filtered: false
remove_mean: false
remove_silent: true
save_results: 1
save_as_svg: 1
smoothing_window: 50 #Ex. 50: 50*0.1=5ms time window
smoothing_window_indiv_neurons: 500 #Original: 500 
sync_regularity: 0
#Plot selection
membrane_potential_plot: 0
raster_plot: 0
rate_coded_plot: 1
